name : CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4 

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      # DVC
      - name: Create credentials.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA > credentials.json

      - name: Modify DVC Remote
        run: |
          uv run dvc remote modify --local gdrive-remote gdrive_service_account_json_file_path credentials.json

      - name: DVC Pull Data
        run: |
          uv run dvc pull -v
      # Run CNN Inference
      - name: Run tests
        run: |
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots
          python3 main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_False.pth

      # Train CNN Model with MLflow
      - name: Train CNN with MLflow
        env:
          SECRET_HOST: ${{ secrets.SECRET_HOST }}
          SECRET_PORT: ${{ secrets.SECRET_PORT }}
          SECRET_USERNAME: ${{ secrets.SECRET_USERNAME }}
          SECRET_PPK_VALUE: ${{ secrets.SECRET_PPK_VALUE }}
        run: |
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots
          python3 main.py --mode train --data_path ./data/train/ --model_path ./models/
